import AppKit

struct ClipboardSnapshot: Equatable {
	struct Representation: Equatable {
		let type: NSPasteboard.PasteboardType
		let data: Data
	}

	let items: [[Representation]]

	var isEmpty: Bool { items.isEmpty }

	static func capture(from pasteboard: NSPasteboard) -> ClipboardSnapshot {
		let items = (pasteboard.pasteboardItems ?? []).compactMap { item -> [Representation]? in
			let representations = item.types.compactMap { type -> Representation? in
				guard let data = item.data(forType: type) else { return nil }
				return Representation(type: type, data: data)
			}
			return representations.isEmpty ? nil : representations
		}
		return ClipboardSnapshot(items: items)
	}

	func restore(to pasteboard: NSPasteboard) {
		pasteboard.clearContents()
		guard !items.isEmpty else { return }
		let pasteboardItems = items.map { representations -> NSPasteboardItem in
			let item = NSPasteboardItem()
			for representation in representations {
				item.setData(representation.data, forType: representation.type)
			}
			return item
		}
		pasteboard.writeObjects(pasteboardItems)
	}
}

enum ClipboardWriter {
	// nspasteboard.org markers: clipboard managers skip transient, auto-generated content
	static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
	static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

	@discardableResult
	static func write(_ text: String, to pasteboard: NSPasteboard, transient: Bool) -> Int {
		pasteboard.clearContents()
		let item = NSPasteboardItem()
		item.setString(text, forType: .string)
		if transient {
			item.setData(Data(), forType: transientType)
			item.setData(Data(), forType: autoGeneratedType)
		}
		pasteboard.writeObjects([item])
		return pasteboard.changeCount
	}

	static func shouldRestore(currentChangeCount: Int, changeCountAfterWrite: Int) -> Bool {
		currentChangeCount == changeCountAfterWrite
	}
}
